export const cities: string[] = ['Ağcabədi', 'Ağdam', 'Ağdaş', 'Ağdərə', 'Ağstafa', 'Ağsu', 'Astara', 'Babək', 'Bakı', 'Balakən', 'Beyləqan', 'Bərdə', 'Biləsuvar', 'Cəbrayıl', 'Cəlilabad', 'Culfa', 'Daşkəsən', 'Xocalı', 'Füzuli', 'Gədəbəy',
    'Gəncə', 'Goranboy', 'Göyçay', 'Göygöl', 'Göytəpə', 'Hacıqabul', 'Horadiz', 'Xaçmaz', 'Xankəndi', 'Xocalı', 'Xocavənd', 'Xırdalan', 'Xızı', 'Xudat', 'İmişli', 'İsmayıllı', 'Kəlbəcər', 'Kürdəmir', 'Qax', 'Qazax', 'Qəbələ', 'Qobustan',
    'Quba', 'Qubadlı', 'Qusar', 'Laçın', 'Lerik', 'Lənkəran', 'Liman', 'Masallı', 'Mingəçevir', 'Naftalan', 'Naxçıvan', 'Neftçala', 'Oğuz', 'Ordubad', 'Saatlı', 'Sabirabad', 'Salyan', 'Samux', 'Siyəzən', 'Sumqayıt', 'Şabran', 'Şahbuz',
    'Şamaxı', 'Şəki', 'Şəmkir', 'Şərur', 'Şirvan', 'Şuşa', 'Tərtər', 'Tovuz', 'Ucar', 'Yardımlı', 'Yevlax', 'Zaqatala', 'Zəngilan', 'Zərdab']
export const regions: string[] = ['Yasamal r.','7-ci mikrorayon q.','Nəsimi r.','Xətai r.','28 May m.','Bakıxanov q.','Nərimanov r.','Gənclik m.','Memar Əcəmi m.','Elmlər Akademiyası m.','İnşaatçılar m.','Binəqədi q.','İçəri Şəhər m.','Mərdəkan q.','Bilgəh q.','Badamdar q.','Yasamal q.',
    'Yeni Yasamal q.','Həzi Aslanov m.','Sahil m.','Masazır q.','8-ci mikrorayon q.','Buzovna q.','Nizami r.','Şüvəlan q.','Yeni Ramana q.','Şimal DRES q.','Şah İsmayıl Xətai m.','Nardaran q.',
    'Ramana q.','Əhmədli q.','Suraxanı q.','Əhmədli m.','Neftçilər m.','20 Yanvar m.','Binə q.','Nizami m.','9-cu mikrorayon q.','Pirşağı q.','Zirə q.','Qara Qarayev m.','Azadlıq Prospekti m.','Xalqlar Dostluğu m.',
    'Keşlə q.','Balaxanı q.','Zabrat q.','Səbail r.','Mehdiabad q.','Məmmədli q.','Biləcəri q.','Binəqədi r.','Abşeron r.','NZS q.','Nəriman Nərimanov m.','Yeni Suraxanı q.','Nəsimi m.','Şıxov q.','Qala q.','8 Noyabr m.','Kürdəxanı q.','Şağan q.','Lökbatan q.','Novxanı q.',
    'Yeni Günəşli q.','8-ci kilometr q.','Zığ q.','4-cü mikrorayon q.','Bayıl q.','Maştağa q.','Qaraçuxur q.','Həzi Aslanov q.','Qobu q.','Savalan q.','Saray q.','Sulutəpə q.','Fatmayı q.','Hökməli q.','Hövsan q.','Xəzər r.','Zağulba q.','Türkan q.','Sabunçu q.','Suraxanı r.',
    'Sahil q.','20-ci sahə q.','Bülbülə q.','Ceyranbatan q.','Qaradağ r.','Dərnəgül m.','M.Ə.Rəsulzadə q.','Avtovağzal m.','Dədə Qorqud q.','Əmircan q.','Kubinka q.','6-cı mikrorayon q.','Xutor q.','Xocəsən q.','Sabunçu r.','Müşviqabad q.','Köhnə Günəşli q.','Bahar q.','Günəşli q.','Dübəndi q.',
    'Görədil q.','Pirəkəşkül q.','3-cü mikrorayon q.','Qobustan q.','28 May q.','Çiçək q.','Səngəçal q.','Pirallahı r.','5-ci mikrorayon q.','2-ci mikrorayon q.','Koroğlu m.','Yeni Corat q.','2-ci Alatava q.','Ələt q.','Bakmil m.','Massiv D q.','Massiv V q.','Böyükşor q.','Ulduz m.','Ağ şəhər ','Massiv A q.','Digah q.','1-ci mikrorayon q.',
    'Puta q.','Köhnə Corat q.','Yeni Balaxanı q.','Massiv B q.','Sea Breeze ']